
name: Plus62 Bordir

title: Produk & Jasa Bordir

description: Produk & Jasa Bordir Manual Tasikmalaya

avatar: /images/thumb.png

image: /images/thumb.png

disqus: 
comen: 
fb-pixel: 
fb-appID: 
fb-admin: 
fb-profile: 
fb-pages: 
signal-id: 
google_analytics: 

url: "https://plus62bordir.netlify.app"

baseurl: ""

permalink: /:title

version: v1.2.0

kramdown:
  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

collections:
  blogs:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 4
paginate_path: '/page-:num'


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
